### ISSUE TITLE
Add verification step for assignment of LB IP

### ISSUE THREAD

**Issue by strieflin** [carbynestack/carbynestack.github.io#15]
Since it can take some time until the IP of the Istio ingress gateway can be queried, it would be advantageous to include a step for verification.
The inexperienced user will easily run into problems during setup. -  We missed this in the previous version

_Originally posted by @sbckr in https://github.com/carbynestack/carbynestack.github.io/pull/14#discussion_r726937638_

**Comment by sbckr** [comment]
I would argue that this issue was resolved with #22. The original intent of this issue was to verify that an IP was assigned, not to verify which IP was assigned. Thus #21 would have been a duplicate

**Comment by strieflin** [comment]
Agree. Will mark as duplicate and close.
