### ISSUE TITLE
Add resource requirements hints

### ISSUE THREAD

**Issue by grevend-bosch** [carbynestack/carbynestack.github.io#19]
Currently, the prerequisites section does not provide recommendations regarding the minimum memory or CPU core count requirements:

https://github.com/carbynestack/carbynestack.github.io/blob/91601e8959b16a3edb90ff40d521682a5ca3b3a1/docs/getting-started/platform-setup.md#L37-L48

This aspect should probably be addressed if those requirements can be measured. Or alternatively, a proven configuration in combination with a warning that the setup might not succeed if not enough resources are available could be added.

**Comment by strieflin** [comment]
I have added numbers (3 GB RAM + 1 CPU core) based on what is reported by `kubectl top` right after having deployed the stack. It is somewhat unclear, however, whether this allows for real world usage. Thus, I marked these numbers as the minimum and added a disclaimer that depending on the deployed workloads requirements might be higher.
